import type { ZReport } from "@/lib/fm-types";

export const zReportFieldLabels: Record<keyof ZReport, string> = {
  DateTime: "Дата/час",
  FiscalCount: "Фіскальний лічильник",
  StornoCount: "Лічильник повернень",
  LastDocument: "Останній документ",
  KSEFNum: "Номер KSEF",
  salesMode: "Режим продажу",
  ObigVatA: "Обіг A",
  ObigVatB: "Обіг Б",
  ObigVatC: "Обіг В",
  ObigVatD: "Обіг Г",
  ObigVatE: "Обіг Д",
  ObigVatAStorno: "Обіг A повернення",
  ObigVatBStorno: "Обіг Б повернення",
  ObigVatCStorno: "Обіг В повернення",
  ObigVatDStorno: "Обіг Г повернення",
  ObigVatEStorno: "Обіг Д повернення",
  SumaVatA: "ПДВ A",
  SumaVatB: "ПДВ Б",
  SumaVatC: "ПДВ В",
  SumaVatD: "ПДВ Г",
  SumaVatE: "ПДВ Д",
  SumaVatAStorno: "ПДВ A повернення",
  SumaVatBStorno: "ПДВ Б повернення",
  SumaVatCStorno: "ПДВ В повернення",
  SumaVatDStorno: "ПДВ Г повернення",
  SumaVatEStorno: "ПДВ Д повернення",
  ZbirVatM: "Обіг M(АБВГД)",
  ZbirVatH: "Обіг H(АБВГД)",
  ZbirVatMStorno: "Обіг M(АБВГД) повернення",
  ZbirVatHStorno: "Обіг H(АБВГД) повернення",
  ZbirVatMTax: "Збір M(АБВГД)",
  ZbirVatHTax: "Збір H(АБВГД)",
  ZbirVatMTaxStorno: "Збір M(АБВГД) повернення",
  ZbirVatHTaxStorno: "Збір H(АБВГД) повернення",
  ZNumber: "Номер Z-звіту",
  FMNumChanges: "",
  LastFiscalizationNum: "",
  TaxNumChanges: "",
  RamResetsCount: "",
};
